### ISSUE TITLE
Not working on M1 Macs

### ISSUE THREAD

**Issue by typeRob** [TheUltimateC0der/Deemixrr#42]
Followed the wiki to start the container, then turned it on, once the custom script load it gives me an error:

deemixrr-deemixrr-1  |    Unhandled exception. System.IO.IOException: Function not implemented
deemixrr-deemixrr-1  |    at System.IO.FileSystemWatcher.StartRaisingEvents()
deemixrr-deemixrr-1  |    at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
deemixrr-deemixrr-1  |    at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
deemixrr-deemixrr-1  |    at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
deemixrr-deemixrr-1  |    at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
deemixrr-deemixrr-1  |    at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
deemixrr-deemixrr-1  |    at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
deemixrr-deemixrr-1  |    at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func` 1 changeTokenProducer, Action changeTokenConsumer)
deemixrr-deemixrr-1  |    at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
deemixrr-deemixrr-1  |    at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
deemixrr-deemixrr-1  |    at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
deemixrr-deemixrr-1  |    at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
deemixrr-deemixrr-1  |    at Microsoft.Extensions.Hosting.HostBuilder.Build()
deemixrr-deemixrr-1  |    at Deemixrr.Program.Main(String[] args) in /src/Deemixrr/Program.cs:line 11
deemixrr-deemixrr-1  | qemu: uncaught target signal 6 (Aborted) - core dumped

**Comment by TheUltimateC0der** [comment]
The problem may be caused by using .Net 5 maybe an update to .Net 6 will fix this.

I don't have a M1 to test nor do I care about if my projects run on apple related stuff tbh. If there is a PR from somebody willing to make it work, I will review and accept it.
